name: Vue3 CI/CD Pipeline

on:
  push:
    branches:
      - main  # 只在推送到 main 分支時觸發
  pull_request:
    branches:
      - main  # 在發送 pull request 時觸發
# env:
#   DEPLOY_KEY: "abc"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢出代碼
      - name: 檢出代碼
        uses: actions/checkout@v2

      # 2. 設定 Node.js 環境
      - name: 設定 Node.js 環境
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 設定 Node.js 版本

      # 3. 安裝依賴
      - name: 安裝依賴與讀取金鑰
        env:
          DEPLOY_KEY: "1234"  # 透過 Secrets 使用私密金鑰
        run: |
          echo DEPLOY_KEY=cde >> .env
          npm install
          node app.js
          # echo "讀取金鑰: ${{secrets.DEPLOY_KEY}}"
          echo "讀取金鑰: ${{env.DEPLOY_KEY}}"
        
          



